create:
  name: Create Persistent Scene
  description: Create a persistent scene by capturing the current state of specified entities.
  fields:
    scene_id:
      name: Scene ID
      description: Identifier for the persistent scene to be created.
      required: true
      selector:
        text:
      example: evening_mode
    snapshot_entities:
      name: Snapshot Entities
      description: List of entity IDs to snapshot.
      required: true
      selector:
        entity:
          multiple: true
      example:
        - light.living_room
        - switch.aircon
    options:
      name: Options
      description: Additional options for scene creation.
      # selector:
      #   object:
      fields:
        restore_light_attributes:
          name: Restore light attributes
          description: Restore brightness, color, etc., even if the light is off.
          selector:
            boolean:
          example: true
          # # filter dose not work why?
          # filter:
          #   attribute:
          #     supported_color_modes:
          #       - light.ColorMode.COLOR_TEMP
          #       - light.ColorMode.HS

delete:
  name: Delete Persistent Scene
  description: Delete a previously created persistent scene.
  fields:
    entity_id:
      name: Scene Entity
      description: The persistent scene entity to delete (e.g., scene.xxx).
      required: true
      selector:
        entity:
          domain: scene
          integration: res_scene
      example: scene.evening_mode
