create:
  name: Create Persistent Scene
  description: Create a persistent scene by capturing the current state of specified entities.
  fields:
    scene_id:
      name: Scene ID
      description: Identifier for the persistent scene to be created.
      required: true
      selector:
        text:
      example: evening_mode
    snapshot_entities:
      name: Snapshot Entities
      description: List of entity IDs to snapshot.
      required: false
      selector:
        entity:
          multiple: true
      example:
        - light.living_room
        - switch.aircon
    snapshot_areas:
      name: Snapshot Areas
      description: Capture all entities belonging to these areas.
      required: false
      selector:
        area:
          multiple: true
      example:
        - living_room
        - kitchen
    snapshot_labels:
      name: Snapshot Labels
      description: Capture all entities having these labels.
      required: false
      selector:
        label:
          multiple: true
      example:
        - nighttime
        - security
    options:
      name: Options
      description: Additional options for scene creation.
      # selector:
      #   object:
      fields:
        restore_light_attributes:
          name: Restore light attributes
          description: Restore brightness, color, etc., even if the light is off.
          selector:
            boolean:
          example: true
          # # filter dose not work why?
          # filter:
          #   attribute:
          #     supported_color_modes:
          #       - light.ColorMode.COLOR_TEMP
          #       - light.ColorMode.HS
        action_timeout:
          name: Action timeout
          description: Timeout in seconds for actions that check results.
          selector:
            number:
              min: 0.5
              max: 120
              step: 0.5
              mode: slider
          example: 20
delete:
  name: Delete Persistent Scene
  description: Delete a previously created persistent scene.
  fields:
    entity_id:
      name: Scene Entity
      description: The persistent scene entity to delete (e.g., scene.xxx).
      required: true
      selector:
        entity:
          domain: scene
          integration: res_scene
      example: scene.evening_mode
